{"name": "test_single_user_not_found", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n  +404\n  -400", "trace": "self = <test_requests.TestGetRequests object at 0x7fcabbda9700>\n\n    def test_single_user_not_found(self):\n        get_req = requests.get('https://reqres.in/api/users/23')\n        get_req_json = get_req.json()\n>       assert get_req.status_code == 400\nE       assert 404 == 400\nE         +404\nE         -400\n\ntest_requests.py:20: AssertionError"}, "start": 1612048411351, "stop": 1612048411793, "uuid": "89cf270b-2678-4a1d-9c1c-edd2ae3e1556", "historyId": "eaf2c4501f3d951cef6f718d8aa6b199", "testCaseId": "adb4cab2bf00c958a764d88657c0f3ff", "fullName": "api_testing.homework3.test_requests.TestGetRequests#test_single_user_not_found", "labels": [{"name": "parentSuite", "value": "api_testing.homework3"}, {"name": "suite", "value": "test_requests"}, {"name": "subSuite", "value": "TestGetRequests"}, {"name": "host", "value": "kali"}, {"name": "thread", "value": "2656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_testing.homework3.test_requests"}]}